apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-express-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-express-app
  template:
    metadata:
      labels:
        app: my-express-app
    spec:
      containers:
      - name: my-express-app
        image: siddharthsutar/myvulapp22
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "1"
            memory: "250Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: my-express-app-service
spec:
  selector:
    app: my-express-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer